language: node_js
node_js:
- '10'
- '12'
- '13'
- '14'
script:
- npm run lint
- npm run build
- npm run test:coverage
- npm run test:coveralls
- npm run docs
deploy:
  - provider: npm
    email: ackeedevelopment@gmail.com
    skip_cleanup: true
    api_key:
      secure: kVyJWhrlxDHd9VwEsdY3zjwRU/oS8zJ3BeaxpjSSwzY2Ss/JOeBHlulZXRnVlVez8JvZGxMqSAg7SvNElFcXR+ADvh4LcnEGz7GB7QNVU2zTmfF5kPm7XUXbI3K9T61y1n3WSWZdePkslkZu2TcgXXFBEEcfMvCjh/uNdJlfVEi34uzvtNgea97DRG7/1rtrHpicKwo5ZvcfZKhVuXW73VKBy8vL9E+wAK2xTVEIEgfs0teA+8XaLw6KQmtU186Olo9XXRN2ILFBfQWDQflUk9K7Zu39p0PpX8aI4VgIf27OYcHhXFrW/FjblGuy4R1EJGDibINBHIJAST7QYXWnS+TYOGCq0UcHWVi7mc7Em9TLSw5q5rI+HJ3uzS9f71GK3JKxI3rrwoBugeJpo4nJ5/f879A/tNfIBuAT2lh01o5J06r6o1qknka/C7GpxhMcSVtqTvtTh2FX4nTc8UddlzZhnO1OJIfONzQkS/TgZXvKgT6p16FRqYXl1AJRAJSMj11lOeMkdLw4jw7EPazLfbIFQYTSCc3Ish/laDg2tZfJ2JrquLB0rxxcdOf5zeCfPhw4HA0zZhs/B6xIMIJ0wrZcNx9a21MaF7XdmnfY4iFPwd/GxsjDLXu+LDNqXpS1NYaOuj3fGyDSezbChcqUNX0CeGrXePcjeZEU7A0rDvA=
    on:
      tags: true
      repo: AckeeCZ/crudella
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: ScyT7X83naCY4/0Xym5rL/2nLlckQ+rLxHGAor4482nHRmPIuZQwKZFAy6KufukJzJW4xDkffGqcdgj+LPc2Md/RyZqfZ8S3lvHzXDkZdB095kwZL3uY4QswYeLqFbfzRygg2hlw7UDONnscxv7o4oxERoN53PaiGGc398+XL9/0MhxnFnDV7AVp5OxBgWDLndTtcah3N5wk4MSYLZVBm5e8AUonr7aMTpKvjubs8Mp1s9mk2p9yYDcr5w8N12Ii/NWNGUFikTD9N6zBuxx9UwKApc6TYkBjGU1FSmNpX9+isudUAc0pQ+x+jsl6Thf0rWamO1073dqvqySb6mfUZbtmrdyHCAs80hEylLR4S+y3MJY9vavVj5Oved1IPKruVltHNeRYefH8fRmg3C3EbXMEY6Us6BWebYPkFujQXanJp1usqJl5WQAnIoZTBavlymEI7I0SeqtZBrI0i5vf76dyLb/nRpkFHmmOEWYUbWXLt4J8rn/Ir+M3oipOmtgnbl7tRZ5ZHrs3J66HHKeTBlmMFs7HzcrqESTR1oyfJe1ZayE+4oesOoSBC5Eg2Ufd39k7P/lfnixdfdDo5ufN1Pbnc6WtWbuiXCuaFzavAYho7E05QIB4bKdxnJ4imBI/k0AFOyuOgRdZ6QKiH+4d6GgR/Xhe0Ik0ce0RF6sH1tc=
    keep-history: true
    local-dir: ./docs
    verbose: true
    on:
      branch: master
