language: node_js
node_js:
- '6'
- '7'
- '8'
- '9'
- '10'
script:
- npm run lint
- npm run build
- npm run test:coverage
- npm run test:coveralls
- npm run docs
deploy:
  - provider: npm
    email: ackeedevelopment@gmail.com
    skip_cleanup: true
    api_key:
      secure: WPySYXAzc1ii0i4KrKWK+49Htm4nZ6uUemNvdmV+nG2BPAMEjytc0dXT117BUpTXeLwWZtcTEKRvtJA/EoXBtVsgnZOWuEMG0AMNqeaNVX2+7W5oK6Nh37yUsPUJhhZ4+kRppj3JZETup8spPxMtE40x+RzFYA6GXfd6YVN2QoMb0oH1vHx569BzketkmczUNC54GPz9p3Cm8W1sXvYpBJmJwmVKAa6Xy9tjv639fxUgD8HIEJFiOUFwX10riRny2KXsSXfOmDsQ8DJZbA6gyyXxAHoh4MQ8vv63U+KH7DV9F/BK+wxYaD7qgLw2/VPigtvUt1dG3rXG8FB2ACxq0DK6ANzR8VENdO7lJ7vZ8Q/mZluwb8dA0tx/BDUHA5ULvqbePAc3WpWAsNXS2jVwgUkkXDPm3/2+Eom0MLYXbPUiNhjn3rdMEr/pZKmUj3RqV4UjEXuqujZtvdUoOzjL912+bGq05oG05Q/az9OVg/hpUdjKJZ7XloHJfytJhQ0JDYCU/Jj2Cn2wCAkGj7cMiN9r3dea5m3/qKYW8pg0kQdLzWFyC48vLfPbXtGFhNe+tXHgFU/AJp9KzDk/sEaMC5xZWUDmhK5Fxtd1892LyJ6p5rD0O+CQvGKCZ+NrOCkYziB2rOYM1DQRhTcIzP3JfdBIgNIc4Nio5ozgsboSReY=
    on:
      tags: true
      repo: AckeeCZ/crudella
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: ScyT7X83naCY4/0Xym5rL/2nLlckQ+rLxHGAor4482nHRmPIuZQwKZFAy6KufukJzJW4xDkffGqcdgj+LPc2Md/RyZqfZ8S3lvHzXDkZdB095kwZL3uY4QswYeLqFbfzRygg2hlw7UDONnscxv7o4oxERoN53PaiGGc398+XL9/0MhxnFnDV7AVp5OxBgWDLndTtcah3N5wk4MSYLZVBm5e8AUonr7aMTpKvjubs8Mp1s9mk2p9yYDcr5w8N12Ii/NWNGUFikTD9N6zBuxx9UwKApc6TYkBjGU1FSmNpX9+isudUAc0pQ+x+jsl6Thf0rWamO1073dqvqySb6mfUZbtmrdyHCAs80hEylLR4S+y3MJY9vavVj5Oved1IPKruVltHNeRYefH8fRmg3C3EbXMEY6Us6BWebYPkFujQXanJp1usqJl5WQAnIoZTBavlymEI7I0SeqtZBrI0i5vf76dyLb/nRpkFHmmOEWYUbWXLt4J8rn/Ir+M3oipOmtgnbl7tRZ5ZHrs3J66HHKeTBlmMFs7HzcrqESTR1oyfJe1ZayE+4oesOoSBC5Eg2Ufd39k7P/lfnixdfdDo5ufN1Pbnc6WtWbuiXCuaFzavAYho7E05QIB4bKdxnJ4imBI/k0AFOyuOgRdZ6QKiH+4d6GgR/Xhe0Ik0ce0RF6sH1tc=
    keep-history: true
    local-dir: ./docs
    verbose: true
    on:
      branch: master
